### ISSUE TITLE
Modifications needed to get this working with SASS

### ISSUE THREAD

**Issue by danimbrogno** [wallabyjs/ngCliWebpackSample#1]
Hi, just tried this out, although the sass-loader is specified in the Wallaby Webpack config,  there is no pattern to match SCSS files in the wallaby files config. In order to get this working I added:

```
{pattern: 'src/**/*.scss', load: false},
```

I also had to add these packages:

"wallaby-webpack": "0.0.23",
"webpack": "2.1.0-beta.22",
"phantomjs-prebuilt": "^2.1.12",
"sass-loader": "^4.0.2",

I assume you would need to follow similar steps to get LESS or stylus working.

Just thought I'd share this tidbit in case this trips anyone else up.

I'm very happy to have Wallaby working together with the webpack version of angular2-cli!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
Yep, the sample is built/generated for CSS, I added the `sass/less-loader` just to make it easier for people to add sass/less if required.
