### ISSUE TITLE
Some issues when trying to setup wallaby

### ISSUE THREAD

**Issue by sasxa** [wallabyjs/ngCliWebpackSample#10]
There seams to be an issue with loading stylus and json files. 

For example:
```
@Component({
  selector: 'app-offline-status',
  template: `<figure [class]="status" [title]="status"></figure>`,
  styleUrls: ['./offline-status.component.styl']
})
```
Throws this error:
```
​​Uncaught Error: Cannot find module "./offline-status.component.styl"​​
  at ​src/app/shared/components/offline/offline-status.component.ts:6​
​​Module not found: Error: Can't resolve './offline-status.component.styl' in '.\src\app\shared\components\offline'Error​​
​​  at factoryCallback (~~\node_modules\webpack\lib\Compilation.js:259:39)​​
  ....
```
In one of my services I'm importing json directly in typescript using json declaration:
```
// src/typings.d.ts
declare module '*.json' {
  const value: any;
  export default value;
}

// src/app/core/config/configuration.service.ts
import config from './config.json';
```
Which throws:

```
​​Uncaught Error: Cannot find module "./config.json"​​
  at ​src/app/core/config/configuration.service.ts:1​
​​Module not found: Error: Can't resolve './config.json' in '.\src\app\core\config'Error​​
​​  at factoryCallback (~~\node_modules\webpack\lib\Compilation.js:259:39)​​
  ....
```
---
Other then errors above, it works with `env.kind = electron`. I tried setting up PhantomJS runner (removed `env`, installed `intl`, improted everything from polyfills into `wallaby.test.ts`), but I'm getting lot of errors:
```
​​Error: Cannot find module '~~\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.48\projects\1fb9f279bf66b3a8\instrumented\src\wallaby.test.js'​​
​​Error: Cannot find module '~~\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.48\projects\1fb9f279bf66b3a8\instrumented\src\app\app.component.spec.js'​​
​SyntaxError: Expected an identifier but found 'AppComponent' instead​​
  at ​src/app/app.component.ts:11​
​​Error: Cannot find module '.\src\wallaby.test.js'​​
​​at http://localhost:7895/wallaby-webpack.js?1490713923310:1​​
​​SyntaxError: Unexpected token ')'​​
  at ​src/app/app.component.spec.ts:7:0​
  ....
```
Errors are mostly these two (few in source files, but mostly in spec files), repeated many times:
- SyntaxError: Expected an identifier but found 'NAME' instead​​
- ​​SyntaxError: Unexpected token ')'​​

Project works with CLI: `ng serve`, `ng build -prod -aot`, `ng test -cc`, etc. all work as expected.

**Comment by ArtemGovorov** [comment]
> There seams to be an issue with loading stylus and json files.

Wallaby [requires all used files](https://wallabyjs.com/docs/config/files.html) to be in the `files` list. I have [added them to the `files` list](https://github.com/wallabyjs/ngCliWebpackSample/commit/a8a9dec47db7611f5bb78ba5535ec53ca041272a), try doing the same and it should work.

> I tried setting up PhantomJS runner 
> Project works with CLI

CLI is using Chrome to run the tests, so Electron runner for wallaby is probably a better (closer) option. 

Regarding the errors with PhantomJs just tried and can't reproduce them. Here's what I have done:
- uncommented all `core-js` polyfills in the `src/polyfills.ts` file
- uncommented the `intl` polyfills (the last line in the `src/polyfills.ts` file) and ran `npm install --save intl`
- commented out the `env: {...}` setting in wallaby config.

If doing the steps above doesn't work for you, could you please share you fork, I'm happy to have a look.
