### ISSUE TITLE
tsconfig.spec.json is not complete by itself

### ISSUE THREAD

**Issue by victornoel** [wallabyjs/ngCliWebpackSample#12]
Hi,

I noticed that `./src/tsconfig.spec.json` refers to `./tsconfig.json`, so normally, to be complete, we should be doing something like that in `wallaby.js`:

```js
var compilerOptions = require('./tsconfig.json').compilerOptions;
Object.assign(compilerOptions, requir('./src/tsconfig.spec.json').compilerOptions);
```

(except maybe for the `baseUrl` property that may be wrong in that case…)

What do you think?

**Comment by ArtemGovorov** [comment]
Makes perfect sense, I have changed wallaby config as per your suggestion.
