### ISSUE TITLE
tsconfig wrongly configured in angular-cli.json

### ISSUE THREAD

**Issue by nelisbijl** [wallabyjs/ngCliWebpackSample#15]
Causing build to fail with:
ENOENT: no such file or directory, stat 'C:\Tests\ngCliWebpackSample\src\tsconfig.json'
Error: ENOENT: no such file or directory, stat 'C:\Tests\ngCliWebpackSample\src\tsconfig.json'

**Comment by ArtemGovorov** [comment]
Thanks for the report, the issue is fixed (the [`angular-cli.json` file was outdated](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/angular-cli.json)).
