### ISSUE TITLE
third party module distributing typescript only can not be loaded

### ISSUE THREAD

**Issue by nelisbijl** [wallabyjs/ngCliWebpackSample#17]
I am using the third party module ng2-markdown-to-html
I added it to this sample in fork: https://github.com/nelisbijl/ngCliWebpackSample
The karma tests are working properly
The wallaby tests however, fail to load this particular module.
I suspect, this is caused by the fact that it is distributed with typescript code only.
I tried anything to get this working but did not succeed.
Any help is appreciated.
If this question should have been posted elsewhere, please tell me

**Comment by ArtemGovorov** [comment]
> I suspect, this is caused by the fact that it is distributed with typescript code only.

It is indeed why it didn't work with the config. This sample wallaby config is using a simplified webpack configuration (without `ts-loader`), so modules are expected to be distributed as JavaScript (and it is normally the case).

The easiest way to make it work is just to include the module to the `files` list so that wallaby can compile it for you (plus process one of the module's files with styles loader because it's using styles URL). I have sent you the [pull request to make it work](https://github.com/nelisbijl/ngCliWebpackSample/pull/1).

**Comment by ArtemGovorov** [comment]
[Here is another (a bit more elegant) solution](https://github.com/nelisbijl/ngCliWebpackSample/pull/2) that uses `@ngtools/webpack` loader for modules distributed as TypeScript only:

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: 'raw-loader'},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],

      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src')
      ]
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.styl', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};


```

**Comment by nelisbijl** [comment]
Thanks, I was able to make these changes in my original project and it works.
My experience of the last months is that getting the various configurations right may take more time than the time spend on writing code.

**Comment by ArtemGovorov** [comment]
> My experience of the last months is that getting the various configurations right may take more time than the time spend on writing code.

It is the sad reality of the modern front-end development. Configurations are just reflecting project's build complexity.
