### ISSUE TITLE
Failed to load. Please call TestBed.compileComponents before your test

### ISSUE THREAD

**Issue by ramaghanta** [wallabyjs/ngCliWebpackSample#19]
I am using https://github.com/temich666/t-json-viewer in my Angular app and ng test works fine. With wallaby, I am getting the following error.

`
    Failed: Uncaught (in promise): Failed to load t-json-viewer.component.html
`

`    
    Failed: This test module uses the component TJsonViewerComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.
`

I am using the wallaby.js configuration from this sample. Any ideas how to resolve this?

**Comment by ArtemGovorov** [comment]
You may add a webpack template loader for the module. This should work for you:

```javascript
  ...
  var webpackPostprocessor = wallabyWebpack({
    ...

    module: {
      loaders: [
        ...
        {test: /\.js$/, loader: 'angular2-template-loader', include: /node_modules\/t-json-viewer/},
      ]
    },
...
```

**Comment by ramaghanta** [comment]
That worked. Thanks for your help.
