### ISSUE TITLE
Failed to parse Spec file, unexpected token

### ISSUE THREAD

**Issue by OClement** [wallabyjs/ngCliWebpackSample#2]
Trying this setup with no success
Just updated everything (Wallaby, Webstorm)

See screenshot
Not sure where to go from there; It complains about a single-quote O_o

<img width="1422" alt="screen shot 2016-09-23 at 12 58 58 pm" src="https://cloud.githubusercontent.com/assets/814862/18794464/a7727d26-818d-11e6-8d52-581a652d216e.png">

**Comment by ArtemGovorov** [comment]
Thanks for the report! We recently added a plugin to wallaby parser and it seems to break on scenarios where `async` is used as a function name. We've removed the plugin and published the fix. Please restart your IDE and start wallaby, it should update the core to 1.0.295 where the issue is fixed.
