### ISSUE TITLE
Cannot load css files using @import

### ISSUE THREAD

**Issue by hieudt** [wallabyjs/ngCliWebpackSample#24]
Hello,

If in your `app.component.css`, you `@import` a css file (e.g. `@import "common.css"`) then Wallaby fails to load `common.css` and reports an error like so:

```
src/app/app.component.spec.ts AppComponent should have as title 'app' [31 ms]

Failed: Uncaught (in promise): Failed to load common.css

Failed: This test module uses the component AppComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.
	at Object.<anonymous> src/app/app.component.spec.ts:17

From console:
	Unhandled Promise rejection: Failed to load common.css ; Zone: ProxyZone ; Task: Promise.then ; Value: Failed to load common.css undefined 
```
See here: https://github.com/hieudt/ngCliWebpackSample

Has anyone had this issue before?

**Comment by ArtemGovorov** [comment]
Thanks for creating the repo! Just adjusted the config: https://github.com/wallabyjs/ngCliWebpackSample/commit/8989f370139c8d00b823d913d291c3f9b4cd780b#diff-4e87b2c6dcfa10beeaf6797eaa6c66ec and also have sent you the [pull request](https://github.com/hieudt/ngCliWebpackSample/pull/1) to make it work.
