### ISSUE TITLE
Multi-app setup

### ISSUE THREAD

**Issue by sasxa** [wallabyjs/ngCliWebpackSample#25]
Angular CLI has support for multiple apps in a project. Nx (https://github.com/nrwl/nx) is also using this feature. I was wondering what's the best practice for setting up wallaby to work with multiple apps/libraries?

I managed to make it work in nx workspace, by creating a common config:

```javascript
// wallaby.config.js

module.exports = function (wallaby, root) {

  var webpackPostprocessor = wallabyWebpack({

    entryPatterns: [
      `${root}/wallabyTest.js`,
      `${root}/**/*spec.js`
    ],

  });
  ...
  return {
    files: [
      { pattern: `${root}/**/*.+(ts|css|less|scss|sass|styl|html|md|json|svg)`, load: false },
      { pattern: `${root}/**/*.d.ts`, ignore: true },
      { pattern: `${root}/**/*spec.ts`, ignore: true }
    ],

    tests: [
      { pattern: `${root}/**/*spec.ts`, load: false },
      { pattern: `${root}/**/*e2e-spec.ts`, ignore: true }
    ],
```
and separate configurations for each app:

```javascript
// wallaby.app1.js

var wallabyConfig = require('./wallaby.config');

var name = 'app1';
var apps = require('./.angular-cli.json').apps;
var root = apps.find(app => app.name = name).root;

module.exports = function (wallaby) {
  return wallabyConfig(wallaby, root);
};


// wallaby.app2.js

var wallabyConfig = require('./wallaby.config');

var name = 'app2';
var apps = require('./.angular-cli.json').apps;
var root = apps.find(app => app.name = name).root;

module.exports = function (wallaby) {
  return wallabyConfig(wallaby, root);
};

```
This works ok with configuration files in root folder, and `wallabyTest.ts` in each app source folder. I'm having some trouble with paths when I try to move these files around. Ideally, I would like to have a structure like this:

```
+-- root
   +-- apps
      +-- app1
          --- wallaby.app1.js
      +-- app2
          --- wallaby.app2.js
   +-- libs
      +-- lib1
          --- wallaby.lib1.js
      +-- lib2
          --- wallaby.lib2.js
   --- package.json
   --- test.js
   --- wallaby.common.js

```

How do I setup patterns and imports to make this work and share common config and bootstrap file?

And a bonus question: Is there a way to setup configuration that would run tests from all apps/libraries?

**Comment by ArtemGovorov** [comment]
Wallaby only supports root config file(s). It doesn't mean that all config code has to be in that file, but the file that is selected as wallaby config has to be in the project's root folder.

So for example, you may have 

```
+-- root
   +-- apps
      +-- app1
      +-- app2
   +-- libs
      +-- lib1
      +-- lib2
   --- package.json
   --- test.js
   --- wallaby.common.js
   --- wallaby.app1.js
   --- wallaby.app2.js
   --- wallaby.lib1.js
   --- wallaby.lib2.js
```

and place most of the logic into the `wallaby.common.js` file, while selecting of the `wallaby.app`/`wallaby.lib` files as an active wallaby configuration. 

So your `wallaby.appX.js`/`wallaby.libX.js` can be one-liners, like:

```javascript
// wallaby.app1.js
module.exports = () => require('./wallaby.common')(wallaby, 'apps/app1');
...
// wallaby.lib1.js
module.exports = () => require('./wallaby.common')(wallaby, 'libs/lib1');
```
and your `wallaby.common.js` file (that can be located anywhere and named the way you like), could look like:
```javascript
// wallaby.common.js
...

module.exports = function (wallaby, root) {

  var webpackPostprocessor = wallabyWebpack({

    entryPatterns: [
      `${root}/wallabyTest.js`,
      `${root}/**/*spec.js`
    ],
    ...
  });
  ...
  return {
  ...
```

Perhaps you may also move the `wallabyTest.ts` file to the root, as I suspect it's going to be the same in all apps/libs.

Some of our users also prefer to have a single config for all apps/libs in the project, [it is also possible](https://github.com/wallabyjs/public/issues/1347).

Please let me know if it answers your question.

**Comment by sasxa** [comment]
Thanks for the info. The link with a single config PR was really useful. I decided to also go with single file config (to many config files otherwise), with the ability to run tests for just one project. Here's the code if someone else is looking for this:

```javascript

var patterns = [
  'apps/*/src/**/*spec.js', 'libs/*/src/**/*spec.js', // run all tests
  // 'apps/app1/src/**/*spec.js',                     // run test just for app1
  // 'libs/lib2/src/**/*spec.js',                     // run test just for lib2
];

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [ 'wallabyTest.js', ...patterns ],
    ...
  });

  return {
    files: [
      { pattern: 'wallabyTest.ts', load: false },
      { pattern: 'apps/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false },
      { pattern: 'apps/**/*.d.ts', ignore: true },
      { pattern: 'apps/**/*spec.ts', ignore: true },
      { pattern: 'libs/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false },
      { pattern: 'libs/**/*.d.ts', ignore: true },
      { pattern: 'libs/**/*spec.ts', ignore: true },
    ],

    tests: [
      { pattern: 'apps/**/*spec.ts', load: false },
      { pattern: 'apps/**/e2e/**', ignore: true },
      { pattern: 'libs/**/*spec.ts', load: false },
      { pattern: 'libs/**/e2e/**', ignore: true },
    ],
    ...
  };
};
```

BTW, why isn't this working:
```javascript
    tests: [
      { pattern: '(apps|libs)/**/*spec.ts', load: false },
      { pattern: '(apps|libs)/**/e2e/**', ignore: true },
    ]
```

**Comment by jasonhick** [comment]
Hey @sasxa, I've been trying to get this to work for an Angular 7 cli generated site with multiple projects and am really struggling! Are you able to share the full files that you managed to get working for this?

**Comment by intuvision** [comment]
I am too having issues with this.  Would it be possible to provide a step-by-step guide?

**Comment by smcenlly** [comment]
@intuvision - can you provide us with a sample repo or exactly what steps you're taking to generate Angular 7 cli-generated site with multiple projects? We'd be happy to take a look at the configuration for you.

**Comment by jasonhick** [comment]
Sample repo setup to use Jest as the testing framework:
https://github.com/jasonhick/gfdtv-ui-services

Generated using the Angular CLI v7.2. Example commands below:
```
ng new test-project --createApplication=false
cd test-project
ng g lib test-library
ng g app test-app
```

**Comment by smcenlly** [comment]
We had some trouble installing npm packages for your sample repo. Having said that, we have it working following the steps you provided.

The first thing I did was follow the steps in the README.md of our [Angular CLI generated project sample](https://github.com/wallabyjs/ngCliWebpackSample#wallabyjs) referenced in [our docs](https://wallabyjs.com/docs/integration/angular.html). I needed to adjust the paths and got this working first in the `test-app`, then in `test-library`. Please find the configuration below.

You should be able to take the same configuration and change the `testFramework` to `jest`. Let us know if you get stuck and we'll take another look at your repo.

```javascript
const wallabyWebpack = require('wallaby-webpack');
const path = require('path');

const compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./projects/test-app/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {
  

  const webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'projects/test-app/src/wallabyTests.js',
      'projects/test-app/src/**/*spec.js',
      'projects/test-library/src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader', options: {paths: [__dirname]}}]},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png|svg)$/, loader: 'raw-loader'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'projects/test-app/src/app'),
        path.join(wallaby.projectCacheDir, 'projects/test-app/src'),
        path.join(wallaby.projectCacheDir, 'projects/test-library/src/app'),
        path.join(wallaby.projectCacheDir, 'projects/test-library/src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'projects/test-app/src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'projects/test-app/src/**/*.d.ts', ignore: true},
      {pattern: 'projects/test-app/src/**/*spec.ts', ignore: true},
      {pattern: 'projects/test-library/src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'projects/test-library/src/**/*.d.ts', ignore: true},
      {pattern: 'projects/test-library/src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'projects/test-app/src/**/*spec.ts', load: false},
      {pattern: 'projects/test-app/src/**/*e2e-spec.ts', ignore: true},
      {pattern: 'projects/test-library/src/**/*spec.ts', load: false},
      {pattern: 'projects/test-library/src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'projects/test-app/src/src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'projects/test-app/src/src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

**Comment by jasonhick** [comment]
Thank you so much for help! Excellent service 👍😃 

Apologies for the duff repo. I'd left in a package that's only used internally and installed via SSH. Ooops. Anyway, I added in the config above and tweaked the path names and it's all working fine. I've spent ages trying to get my head round this! 

I've also created a new dummy repo with this config in it in case anyone else is interested.

Just need to work out the Jest part now ;)

**Comment by wilgert** [comment]
An additional challenge can occur when you are using Nx: you might have mixed test runners i.e. apps that use Karma/Jasmine and libs that use Jest.

I've tried to create a dynamic wallaby config file using the contents of angular.json but I wonder if it is even possible to have wallaby start both test runners?

**Comment by ArtemGovorov** [comment]
> but I wonder if it is even possible to have wallaby start both test runners?

Unfortunately Wallaby can't start 2 testing frameworks at the moment. The best solution I can think of is to have multiple Wallaby config files (and running them separately).

**Comment by wilgert** [comment]
That was my assumption. Thanks for the confirmation from the horse's mouth!

**Comment by wilgert** [comment]
I finally found the time to fix the dynamic wallaby.jest.js config file as well: https://gist.github.com/wilgert/1bfb72db97a53465897f669c29e72916

You have to switch between running wallaby for karma and wallaby for jest in your project, but apart from that this works well and prevents you from having to create any additional files in your project.
