### ISSUE TITLE
wallaby.js with jest as testFramework

### ISSUE THREAD

**Issue by paesku** [wallabyjs/ngCliWebpackSample#26]
Is there a way to setup wallaby.js with **jest**, so that we can use `test('example', () => expect())` in our .spec files? When I change the framework to `testFramework: 'jest'` wallaby in WebStorm complains with **Test framework [jest] is not supported**.

**Comment by ArtemGovorov** [comment]
> When I change the framework to `testFramework: 'jest'` wallaby in WebStorm complains with **Test framework [jest] is not supported**.

This is because this repo setup is for browser environment, and Jest runs in node.

If you have a working Jest configuration for your project (and can run Jest CLI without wallaby), then Wallaby config is trivial - you may find [the docs how to create it here](https://wallabyjs.com/docs/integration/jest.html).

**Comment by paesku** [comment]
@ArtemGovorov Thank you for your help. Finally [this](https://github.com/wallabyjs/public/issues/1236) setup did help me, find the right settings for angular with jest.

The wallaby.js file now looks like the follow, and maybe it's worth adding such a setup to the docs. 

```javascript
const compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {
  return {
    files: [
      'src/setupJest.ts',
      'src/app/**/*.ts',
      'src/app/**/*.html',
      '!src/app/**/*.spec.ts',
      'src/**/*.json',
    ],

    tests: ['src/app/**/*.spec.ts'],

    testFramework: 'jest',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      type: 'node',
      params: 'node'
    },

    setup: function (wallaby) {
      const jestPreset = require('./package.json').jest;
      wallaby.testFramework.configure(jestPreset)
    },

    debug: true
  };
};
```

**Comment by ArtemGovorov** [comment]
@paesku Awesome, thanks for sharing! Have added the [config link to the repo readme](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/README.md#wallaby-configuation-for-jest).
