### ISSUE TITLE
Error in Angular CLI Universal implementation

### ISSUE THREAD

**Issue by goelinsights** [wallabyjs/ngCliWebpackSample#29]
Implementing Angular Universal and getting the following on turning on the express server.

Getting the following error on running: npm run webpack:server
`TS2339: Property '__moduleBundler' does not exist on type 'Window'.` for file wallaby.ts in the root.

Is there a type that needs to be updated for window?  Should the file be excluded from typechecking (error also shows up in lint)?

**Comment by ArtemGovorov** [comment]
Yes, you may exclude wallaby config file from type checking (it's not TypeScript bu JavaScript anyway) and also configure your linter to ignore it.
