### ISSUE TITLE
Postprocessor run failure: Invalid Webpack configuration object

### ISSUE THREAD

**Issue by murraybauer** [wallabyjs/ngCliWebpackSample#3]
Using vscode.
ran `npm install`
Started wallaby, says 0 tests and console says:

`
[Error] ​​Postprocessor run failure: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.​​
[Error] ​​ - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:​​
[Error] ​​   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }​​
`

Looks like something to do with this config in wallaby.js
`postprocessor: webpackPostprocessor,`

**Comment by ArtemGovorov** [comment]
I have updated the sample `package.json` file, try deleting node modules and running `npm install` again.
