### ISSUE TITLE
App Aliases and Wallaby.js

### ISSUE THREAD

**Issue by philipooo** [wallabyjs/ngCliWebpackSample#30]
Hey guys

I recently tried to make use of Aliases to make my code more clear when referencing other modules as you can see here at the "2. Aliases for app and environments" section: https://medium.com/@tomastrajan/6-best-practices-pro-tips-for-angular-cli-better-developer-experience-7b328bc9db81

### Added lines to ./tsconfig.json (for the Webstorm IDE)

    "baseUrl": "./",
    "paths": {
        "@domain/*": ["src/app/domain/*"]
    }

### Added lines to ./src/tsconfig.app.json and ./src/tsconfig.spec.json (for Angular CLI)

    "paths": {
        "@domain/*": ["app/domain/*"]
    }

Now `ng build` and `ng test` works fine. But not Wallaby.js. In Wallaby.js I get errors saying 

    Uncaught Error: Cannot find module "@domain/xyz"
	at src/app/abc/service.ts:7

I am not sure what I have to modify to make Wallaby.js work again. Maybe someone can help?

Cheers

**Comment by ArtemGovorov** [comment]
Hey,

Sure we have a similar use case [described here in the docs](https://wallabyjs.com/docs/integration/typescript.html#typescript-compileroptionspaths-setting). For aliases you'll need [webpack's `resolve.alias`](https://webpack.js.org/configuration/resolve/#resolve-alias). IIRC, for your specific case it may look like:

```javascript
...

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    ...

    resolve: {
      ...
      modules: [
        ...
      ],
      alias: {
        '@domain': path.join(wallaby.projectCacheDir, 'src/app/domain')
      }
    },
    ...
  });

  return {
    ...
  };
};
```

**Comment by philipooo** [comment]
As always, thank you for your awesome support!

**Comment by jkyoutsey** [comment]
I get that "alias" isn't valid:

```
    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/main/ui/app'),
        path.join(wallaby.projectCacheDir, 'src/main/ui'),
        '../../../node_modules'
      ],
      alias: {
        '@environment': path.join(wallaby.projectCacheDir, 'src/main/ui/environments'),
        '@assets': path.join(wallaby.projectCacheDir, 'src/main/ui/assets'),
        "@angular": path.join(wallaby.projectCacheDir, '../../../node_modules/@angular'),
        "@utils": path.join(wallaby.projectCacheDir, 'src/main/ui/app/utils'),
        "@shared": path.join(wallaby.projectCacheDir, 'src/main/ui/app/shared'),
        "@models": path.join(wallaby.projectCacheDir, 'src/main/ui/app/models'),
        "@core": path.join(wallaby.projectCacheDir, 'src/main/ui/app/core'),
      }
    },
```

```
[Error] ​​Postprocessor run failure: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.​​
[Error] ​​ - configuration has an unknown property 'alias'. These properties are valid:​​
[Error] ​​   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }​​
[Error] ​​   For typos: please correct them.​​
[Error] ​​   For loader options: webpack 2 no longer allows custom properties in configuration.​​
[Error] ​​     Loaders should be updated to allow passing options via loader options in module.rules.​​
[Error] ​​     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:​​
[Error] ​​     plugins: [​​
[Error] ​​       new webpack.LoaderOptionsPlugin({​​
[Error] ​​         // test: /\.xxx$/, // may apply this only for some modules​​
[Error] ​​         options: {​​
[Error] ​​           alias: ...​​
[Error] ​​         }​​
[Error] ​​       })​​
[Error] ​​     ]​​
```

**Comment by splintor** [comment]
Works like a charm, thanks!
I think it should be added to [the documentation](https://wallabyjs.com/docs/integration/typescript.html#typescript-compileroptionspaths-setting).
