### ISSUE TITLE
vs code wallaby in angular 6 will not start

### ISSUE THREAD

**Issue by LPCmedia** [wallabyjs/ngCliWebpackSample#31]
Getting an error on linux ubuntu and angular 6 multiproject library build. 

[Error] ​​SyntaxError: /home/pboudreau/dev/activia/activia-ngx-components/tsconfig.json: Unexpected token } in JSON at position 465​​
[Error] ​​    at JSON.parse (<anonymous>)​​
[Error] ​​    at Object.Module._extensions..json (module.js:662:27)​​
[Error] ​​    at Module.load (module.js:556:32)​​
[Error] ​​    at tryModuleLoad (module.js:499:12)​​
[Error] ​​    at Function.Module._load (module.js:491:3)​​
[Error] ​​    at Module.require (module.js:587:17)​​
[Error] ​​    at Module.r.require (/home/pboudreau/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.84/wallaby/server.js:20:12596)​​
[Error] ​​    at require (internal/module.js:11:18)​​
[Error] ​​    at Object.<anonymous> (/home/pboudreau/dev/activia/activia-ngx-components/wallaby.conf.js:5:3)​​

see master of https://github.com/LPCmedia/cm-components

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo. Looks like your `tsconfig.json` is not a valid JSON file, if you delete the [trailing command on line 20](https://github.com/LPCmedia/cm-components/blob/master/tsconfig.json#L20) (the file and the position is also mentioned in the error message), then it should work for you.

**Comment by LPCmedia** [comment]
Thanks should of known to look for something like that
