### ISSUE TITLE
​​Failed: Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js​​

### ISSUE THREAD

**Issue by KiransHub** [wallabyjs/ngCliWebpackSample#33]
Running Wallaby on an Angular6 project I am getting the following error: 

​​Failed: Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js​​

This is causing all tests to fail. My node modules does have a zone.js/dist/zone-testing.js file. 

Here's my wallabyTests.ts: 

`import './polyfills';

import 'zone.js/dist/zone-testing';

import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);`

and here my wallaby.conf.js:

`
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader', options: {paths: [__dirname]}}]},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png|svg)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: true},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

`

I'd really appreciate your help in setting this up. It's taking ages.

Kiran

**Comment by ArtemGovorov** [comment]
I would suggest checking that `src/wallabyTest.ts` file is in the right place. If it is, then please:
- try cloning this repo, run `npm i` and run Wallaby to see if it's working for you.
- if this repo is working, please share a sample repo demonstrating the issue, we are happy to help with the config.

**Comment by KiransHub** [comment]
Silly me! It seems that the file was called WallabyTests.ts not WallabyTest.ts!

**Comment by KiransHub** [comment]
Now I'm getting a slightly different issue through: 

    ​​Failed: Uncaught (in promise): Failed to load ../../theme.css​​
    ​​​​
    ​​Failed: This test module uses the component NavbarComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.​​
      at t.<anonymous> ​src/app/app.component.spec.ts:23:4​
    ​​​​​​​​​​
    ​​​​​From console:​​​​​
      ​​​​​​​​​​
      ​​​​​Unhandled Promise rejection: Failed to load ../../theme.css ; Zone: ProxyZone ; Task: Promise.then ; Value: Failed to load ../../theme.css undefined​​​​​



I tried calling compile component again before the test just to make sure: 


`import { TestBed, async } from '@angular/core/testing';
import { AppComponent } from './app.component';
import { NavbarComponent } from './navbar/navbar.component';
import { SideMenuComponent } from './side-menu/side-menu.component';
import { RouterTestingModule } from '@angular/router/testing';



describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent,
        NavbarComponent,
        SideMenuComponent,
      ],
      imports:[RouterTestingModule]
 
    }).compileComponents();
  }));
  it('should create the app', async(() => {
    
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));`

**Comment by ArtemGovorov** [comment]
Where is the `theme.css` file located relatively to your project's root? Make sure the file path is in one of the `files` patterns (or add it separately).

**Comment by chase-swanson** [comment]
@KiransHub If you have not done so already, you may need to add that css file as an input to the `styles` array under `test` section of your angular.json file.

I am curious if regular Karma test runner is giving the same error?
