### ISSUE TITLE
Wrong file mentioned

### ISSUE THREAD

**Issue by Janatbek** [wallabyjs/ngCliWebpackSample#39]
in readme.md 
Exclude the src/wallabyTest.ts file in the tsconfig.json as it may affect Angular AOT compilation.
points to tsconfig.app.json but in readme it says to exclude it in tsconfig.json

which one is correct?

**Comment by smcenlly** [comment]
The `tsconfig.json` reference in the `readme.md` includes a url that points to `./src/tsconfig.app.json`, which is the correct place to exclude this file from your application. We refer to it as `tsconfig.json` for brevity. The `tsconfig.app.json` file is the `tsconfig` file for your application, and extends the base `./tsconfig.json` file.
