### ISSUE TITLE
When I change the test framwork from jasmime to mocha, error happening.

### ISSUE THREAD

**Issue by lygstate** [wallabyjs/ngCliWebpackSample#4]
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​TypeError: undefined is not an object (evaluating 'mochaOriginal.beforeEach.apply')​​
​​at http://localhost:55022/__modules/260.js?1481485588642:127​​
​​TypeError: undefined is not an object (evaluating 'mochaOriginal.describe.apply')​​
​​at http://localhost:55022/__modules/260.js?1481485588642:100​​
​​TypeError: undefined is not an object (evaluating 'mochaOriginal.beforeEach.apply')​​
  at ​src/wallabyTest.ts:11:0​
​​TypeError: undefined is not an object (evaluating 'mochaOriginal.describe.apply')​​
  at ​src/app/app.component.spec.ts:7:0​

**Comment by ArtemGovorov** [comment]
In order to use mocha, you'll need to [update to the latest version wallaby.js core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). 

Also you'll need to specify the mocha version in the `testFramework` setting (because the default version of mocha when you just specify `mocha` doesn't support some APIs used in the `zone.js/dist/mocha-patch`). Plus, if you're using `chai` with mocha, and not importing it anywhere else (like in the `wallabyTest.ts`), youmay need to load it as well:
```javascript
...
module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'node_modules/chai/chai.js', instrument: false}, // <-- if you're using chai
      ...
    ],

    ...

    testFramework: 'mocha@3.2.0', // <--

    ...
    setup: function () {
      window.expect = chai.expect; // <-- or whatever assertion style you use
      ...
    }
  };
};
```

**Comment by lygstate** [comment]
Could you provide a demo for it?

**Comment by ArtemGovorov** [comment]
Demo for what exactly and what do you mean by demo?

**Comment by lygstate** [comment]
ngCliWebpackSample-mocha

**Comment by ArtemGovorov** [comment]
Well `angular-cli` doesn't support mocha, so I'm not sure maintaining a full sample for it is a good idea. 

Is there something that doesn't still work for you with the changes I have listed? It works for me when I make the changes to the config that I have specified above, update `zone.js` to latest, and [change this](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts#L6) code to import `zone.js/dist/mocha-patch`.

**Comment by lygstate** [comment]
I can running test with mocha, just can not runnning test inside wallabyjs @ArtemGovorov

**Comment by ArtemGovorov** [comment]
So what exactly is not working for, what errors are you getting in wallaby.js after you make the above described changes?

**Comment by ArtemGovorov** [comment]
So I forked the repo and applied the changes I mentioned above, you may find the working solution sample: https://github.com/ArtemGovorov/ngCliWebpackSample

**Comment by lygstate** [comment]
got what's happening
wallabyjs doesn't support the following tests:
```
  it('testing async await', async function () {
   await Promise.resolve(1)
  });
```

**Comment by lygstate** [comment]
It's not about the mocha,  but karma support for that.

**Comment by ArtemGovorov** [comment]
Wallaby.js supports 
```javascript
it('testing async await', async function () {
   await Promise.resolve(1)
});
```
It is just the sample is using TypeScript 2.0.x and it compiles `async`/`await` to ES6 generator functions (despite the target being set to `es5` in the `tsconfig.json`). Generator functions are supported in Chrome, so it works in when you have karma configured to run tests in Chrome. Wallaby.js by [default is using PhantomJs](https://wallabyjs.com/docs/integration/phantomjs2.html) and most of ES6, including generator functions, are not supported in PhantomJs.

The new TypeScript 2.1 version correctly compiles `async`/`await` to ES5, so if you `npm install typescript@2.1.4 --save-dev`, it should work for you. I [have updated the sample](https://github.com/ArtemGovorov/ngCliWebpackSample/blob/master/package.json#L45) I shared earlier to work with your test.

Alternatively, if you need to stick to the TypeScript v2.0.x, you may [configure wallaby to use Chrome V8 (via Electron runner)](https://wallabyjs.com/docs/integration/electron.html) and it will work for you as well with the TypeScript v2.0.x (it'll be similar like running tests in Chrome):
```javascript
...
module.exports = function (wallaby) {
  return {
    ...

    env: {
      kind: 'electron'
    }
  };
};
```
plus

```
npm install electron --save-dev
```
