### ISSUE TITLE
Cannot find module '.\src\wallabyTest.js'​​

### ISSUE THREAD

**Issue by kambizalipour** [wallabyjs/ngCliWebpackSample#40]
I have an Angular 7 CLI project with 700+ tests which all are passing using ng test command. 
I followed the instructions in this sample and used the exact files from the project to setup wallaby.js but it fails with the following errors after running 112 tests (all 112 passed).

​​Uncaught Error: Cannot find module '.\src\wallabyTest.js'​​
​​Uncaught Error: Cannot find module '26'​​

**Comment by smcenlly** [comment]
Can you please send us your wallaby configuration or else a sample repo so we can investigate your specific project details/error?

**Comment by ArtemGovorov** [comment]
Please also try adding this setting to your config:

```diff
...
  return {
+   workers: { initial: 1, regular: 1 }
    files: [
      ...
    ],
...
```

**Comment by kambizalipour** [comment]
Thanks @ArtemGovorov 
That fixed the problem.
