### ISSUE TITLE
Coverage of projects (libraries) with new wallaby.js setup

### ISSUE THREAD

**Issue by cdcarson** [wallabyjs/ngCliWebpackSample#43]
Hi,

This is a question.

I'm using VSCode 1.36.1  and Wallaby 1.0.137.

 ([My example repo is here](https://github.com/cdcarson/wallaby-with-libraries))

With a clean Angular application plus a library, using the current wallaby.js from this repo,  I'm getting the following message in the Wallaby panel:

`Specified entry pattern "projects/my-library/src/**/*spec.js" does not match any file.`

Is the intention that the wallaby.js in the root directory should take care of running the library tests as well? In that case, shouldn't line 46-51 in wallaby.js read...

```ts
   tests: [
      // replace applications.map with projects.map...
      ...projects.map(project => ({
           pattern: project.sourceRoot + specPattern,
           load: false
      }))
    ],

```
This works, at least for me. That is, all the app tests and all the project tests run, and the error message goes away.  There's a huge upside in not having to configure each project separately. And I don't see a downside, really. 

But I just wanted to check first to see whether that is what you intended, or if you can see a downside.  Thanks,

Chris

**Comment by smcenlly** [comment]
Thanks for pointing this out. There's no reason we can't load replace `applications` with `projects`. As your rightly point out, this will then run tests for libraries and applications.
